spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
    show-sql: false

server:
  port: ${SERVER_PORT:8080}

app:
  storage:
    type: s3
    s3:
      bucket: ${AWS_S3_BUCKET}
      region: ${AWS_S3_REGION}
      base-url: ${AWS_S3_BASE_URL}